# Generated by Django 6.0.1 on 2026-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(help_text='ImgBB image URL', max_length=1000)),
                ('category', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('finance', 'Finance'), ('relationships', 'Relationships')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
