# Generated by Django 6.0.1 on 2026-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('spiritual_growth', 'Spiritual Growth & Discipleship'), ('ministry_leadership', 'Ministry & Leadership'), ('relationships_family', 'Relationships & Family'), ('personal_development', 'Personal Development'), ('business_finance', 'Business & Finance'), ('communication_influence', 'Communication & Influence'), ('purpose_destiny', 'Purpose & Destiny')], max_length=100),
        ),
    ]
